services:
  cpp:
    build: .
    volumes:
      - ./project:/project
      - ./data:/data
      - ./project/demo/static:/static
    working_dir: /project
    ports:
      - 80:80
    command: 
      "make"
